[tool.poetry]
name = "sfu-tf-lib"
version = "1.0.0"
description = "Libraries that support the development of machine learning models in TensorFlow."
authors = ["Anderson de Andrade <anderson_de_andrade@sfu.ca>"]
exclude = ["tests/*"]

[[tool.poetry.source]]
name = "private"
url = "https://pypi.org/simple"
secondary = true

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
sfu-data-io = ">=0.1, <1"
mlflow-skinny = "^1.8"
numba = ">=0.51, <1"
numpy = "*"
scikit-learn = ">=0.24, <1"
scipy = "^1.4"
tensorflow = "^2.2"

[tool.poetry.dev-dependencies]
defopt = "*"
flake8 = "*"
mypy = "*"
pytest = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
