[tool.poetry]
name = "terraform_install"
version = "0.1.2"
description = "Installs Terraform to virtualenv bin"
authors = ["Josh Wycuff <Joshua.Wycuff@turner.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
terraform_version = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
