[tool.poetry]
name = "akerbp.mlpet"
version = "1.0.0"
description = "Package to prepare well log data for ML projects."
authors = [
    "Flavia Dias Casagrande <flavia.dias.casagrande@akerbp.com>",
    "Saghar Asadi <saghar.asadi@akerbp.com>",
    "Yann Van Crombrugge <yann.vancrombrugge@akerbp.com>"
]
packages = [
    { include = "akerbp/mlpet", from = "src" },
]
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
]
repository = "https://bitbucket.org/akerbp/akerbp.mlpet/src/master/"
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
PyYAML = "5.4.1"
imbalanced-learn = ">=0.8.0"
cognite-sdk = ">=2.31.0"
joblib = "1.0.1"
numpy = ">=1.19.5"
pandas = ">=1.3.2"
scikit-learn = ">=0.24.2"
scipy = ">=1.7.1"

[tool.poetry.dev-dependencies]
pylint = "^2.11.1"
flake8 = "^4.0.1"
black = "^21.11b1"
pdoc = "^8.0.1"
pre-commit = "^2.15.0"
mypy = "^0.910"
bandit = "^1.7.1"
types-PyYAML = "^6.0.1"
ipython = "^7.30.1"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
