
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: aio.functional:package

from setuptools import setup

setup(**{
    'author': 'Ryan Northey',
    'author_email': 'ryan@synca.io',
    'description': 'A collection of functional utils for asyncio',
    'install_requires': (
    ),
    'license': 'Apache Software License 2.0',
    'long_description': """
aio.functional
==============

Function utils for asyncio.
""",
    'maintainer': 'Ryan Northey',
    'maintainer_email': 'ryan@synca.io',
    'name': 'aio.functional',
    'namespace_packages': (
    ),
    'package_data': {
        'aio.functional': (
            'py.typed',
        ),
    },
    'packages': (
        'aio.functional',
    ),
    'url': 'https://github.com/envoyproxy/pytooling/tree/main/aio.functional',
    'version': '0.0.10',
})
