[tool.poetry]
name = "cwscript"
version = "0.1.0"
description = "CWScript compiler and standard tooling."
authors = ["William Chen <william@terran.one>"]
packages = [
    { include = "cwscript" },
    { include = "cwsls" },
    { include = "cwsc" },
]

[tool.poetry.scripts]
cwsc = "cwsc:main"
cwsls = "cwsls:start_server"
cws-highlight = "cwscript.highlight:main"

[tool.poetry.dependencies]
python = "^3.8"
Jinja2 = "^3.0.3"
antlr4-python3-runtime = "^4.9.3"
pygls = "^0.11.3"
python-fire = "^0.1.0"
click = "^8.0.3"
prompt-toolkit = "^3.0.24"
Pygments = "^2.11.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
maturin = "^0.12.4"
isort = "^5.10.1"
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
