
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T11:17:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "322249f6c9ac9485fa1d5bf380caccc1800f1805",
 "version": "0.7.1.post.dev313"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
