
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-16T15:33:13-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4203454ca236ff652b6bc3f7cac4e6c963fdf77",
 "version": "v0.1.5.post.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
