# Generated by Django 4.0 on 2022-01-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uscalt-drf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentSilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, default=None, max_length=100)),
                ('link', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
