[tool.poetry]
name = "carooline-tecrmi-seamless"
version = "0.3.0"
description = ""
authors = ["Philippe L'ATTENTION <philippe.lattention@hotmail.fr>"]
readme = "README.md"

[tool.poetry.scripts]
carooline-tecrmi-seamless = "carooline_tecrmi_seamless.main:app"

[tool.poetry.dependencies]
python = "^3.6"
zeep = "^4.1.0"
python-dotenv = "^0.19.2"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^21.12b0", allow-prereleases = true}
mypy = "^0.931"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
