name: cytonic
version: 0.1.2
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
description: A Python framework to define REST APIs and automatically generate server side bindings and clients.
license: MIT
url: https://gitea.nkl.st/_/cytonic
typed: true
requirements:
  - python ^3.10
  - databind.json ^1.3.2
  - nr.util ^0.2.1
  - pyyaml ^5.4
extra-requirements:
  fastapi:
    - fastapi ^0.70.1
test-requirements:
  - types-pyyaml
test-drivers:
  - type: mypy
  - type: pytest
dev-requirements:
  - uvicorn ^0.16.0
entrypoints:
  console_scripts:
    - cytonic-codegen-python = cytonic.codegen.python:main
