
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-12T11:04:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e3cace6642eda3ce6e4a582a77b26ce2b36c4d8",
 "version": "1.11.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
