name: rtds
channels:
  - defaults
dependencies:
  - python=3.9
  - gcc_linux-64
  - gxx_linux-64
  - numpy
  - scipy
  - pip
  - pip:
      - ..[docs]
      - "sphinx-book-theme @ git+https://github.com/dfm/sphinx-book-theme.git@fix-outdir"
