
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-09T15:09:43-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "d88ed38f3c5fb9da143ed5bd776300864879d686",
 "version": "1.6.0rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
