[tool.poetry]
name = "lms-id-generator"
version = "0.0.5"
description = "ID generator for lms"
authors = ["DewMaple <dew.maple@gmail.com>"]

[[tool.poetry.source]]
name = 'aliyun'
url = 'https://mirrors.aliyun.com/pypi/simple/'
default = true

[tool.poetry.dependencies]
python = "^3.6"
PyMySQL = "^1.0.2"
importlib-resources = "^5.1.3"
peewee = "^3.14.4"
cryptography = "^3.4.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
mypy = "^0.910"
wheel = "^0.37.1"
twine = "^3.4.1"
pytest-xprocess = "^0.18.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
