
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-08T18:43:22+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b9d06db53f4ba0d5b74ba90364aad9b352a94a61",
 "version": "2.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
