
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-12T20:50:39+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "13219d27a6ca3fb3af62fac97f57d184a3073a88",
 "version": "0.2.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
