[tool.poetry]
name = "pelican-captions"
version = "0.3.3"
description = "Add captions and labels to figures, tables and code blocks."
authors = ["Fabian Köhler <fabian.koehler@protonmail.ch>"]
license = "AGPL-3.0"
readme = "README.md"
keywords = ["pelican", "plugin"]
repository = "https://github.com/f-koehler/pelican-captions"
documentation = "https://docs.getpelican.com"
packages = [{ include = "pelican" }]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Framework :: Pelican",
    "Framework :: Pelican :: Plugins",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.urls]
"Funding" = "https://donate.getpelican.com/"
"Issue Tracker" = "https://github.com/f-koehler/pelican-captions/issues"

[tool.poetry.dependencies]
python = ">=3.6.1,<4.0"
pelican = "^4.5"
markdown = { version = "^3.2.2", optional = true }
beautifulsoup4 = "^4.9.3"

[tool.poetry.dev-dependencies]
black = { version = "^20.8b1", allow-prereleases = true }
flake8 = "^4.0"
flake8-black = "^0.2.0"
invoke = "^1.3"
isort = "^5.4"
livereload = "^2.6"
markdown = "^3.2.2"
pytest = "^6.0"
pytest-cov = "^3.0"
pytest-pythonpath = "^0.7.3"
pytest-sugar = "^0.9.4"
Werkzeug = "^2.0"
pre-commit = "^2.12.1"
mypy = "^0.931"
types-beautifulsoup4 = "^4.9.0"

[tool.poetry.extras]
markdown = ["markdown"]

[tool.autopub]
project-name = "captions"
git-username = "f-koehler"
git-email = "fabian.koehler@protonmail.ch"

[tool.isort]
# Maintain compatibility with Black
profile = "black"
multi_line_output = 3

# Sort imports within their section independent of the import type
force_sort_within_sections = true

# Designate "pelican" as separate import section
known_pelican = "pelican"
sections = "FUTURE,STDLIB,THIRDPARTY,PELICAN,FIRSTPARTY,LOCALFOLDER"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
