
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-12T16:08:10-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a0908a5e1a3ad18a37d38ec1a238d2170ed4f2dc",
 "version": "1.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
