[tool.poetry]
name = "cloops"
version = "0.0.1"
description = "sdfsdfsdfsdf"
authors = ["Your Name <you@example.com>"]
license = "asdasdasdasdasd"

[tool.poetry.dependencies]
python = "3.10.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
