version: "3"
services:
  selenium-hub:
    image: summasolutions/selenium:hub
    container_name: selenium-hub
    volumes:
      - ./:/selenium
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=24
      - GRID_TIMEOUT=120 #Time in seconds the hub waits without a driver activity before killing it
      - GRID_NEW_SESSION_WAIT_TIMEOUT=120 #The time new drivers waits for a slot to become available
    networks: ['selenium-grid']
networks: {selenium-grid: {}}