[tool.poetry]
name = "flox-core"
version = "0.2.0"
description = "Core library for flox"
authors = ["Michal Przytulski <michal@przytulski.pl>", "Daniel Ancuta <whisller@gmail.com>"]
license = "MIT"

packages = [
    { include = "floxcore" }
]

[tool.poetry.dependencies]
python = "^3.6.2"
python-box = "^5.3"
anyconfig = "^0.10"
wasabi = "^0.9"
tqdm = "^4.58"
click = "^7.1"
lazy-load = "^0.8.2"
loguru = "^0.5"
plumbum = "^1.7"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
isort = "^5.10"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
