


__version__ = "0.2022.1.12.1"



from .MediaWikiLocalSettingsArrayAppend import MediaWikiLocalSettingsArrayAppend
from .MediaWikiLocalSettingsComplexVariableAssignment import MediaWikiLocalSettingsComplexVariableAssignment
from .MediaWikiLocalSettingsVariableAssignment import MediaWikiLocalSettingsVariableAssignment
from .MediaWikiLocalSettingsFile import MediaWikiLocalSettingsFile