[tool.poetry]
name = "pyaaware"
version = "1.3.8"
description = "Aaware Python development libraries"
authors = ["Jason Calderwood <jason@aaware.com>"]
maintainers = ["Jason Calderwood <jason@aaware.com>"]
homepage = "http://aaware.com"
license = "GPL-3.0-only"
include = ["pyaaware/pyaaware.cpython-36m-x86_64-linux-gnu.so"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
h5py = ">=2.10.0,<2.11.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
