[tool.poetry]
name = "mo-python"
version = "0.0.1"
description = "A python package for adding alerts to the MO alerts database."
authors = ["Gavin Bell <gavin.bell@optimeering.com>", "Jo Vederhus <jo.vederhus@optimeering.com>"]
license = "Apache-2.0"
packages = [{include = "moalerts"}]

[tool.poetry.dependencies]
python = "^3.8,<4"
pandas = "^1.3.5"
psycopg2 = "^2.9.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"