
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-14T11:58:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "750e52dcd991d87a0817fea4f8854b0b7c327480",
 "version": "0.7.1.post.dev305"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
