
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-15T07:41:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "09b63cd12e9eb1c6914c9b9186684a891e28979c",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
