
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T11:22:00+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "37baf37e9662a6ffd50ed3a66603770838072720",
 "version": "1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
