dist: xenial
sudo: false
language: python

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.wheels
    - PIP_FIND_LINKS=file://$PIP_WHEEL_DIR

matrix:
  include:
    - python: '3.6'
      env: TOXENV=docs
    - python: '3.6'
      env: TOXENV=flake8
    - python: '2.7'
      env: TOXENV=py27
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37
    - python: '3.8'
      env: TOXENV=py38
    - python: '3.9-dev'
      env: TOXENV=py39
    - python: 'pypy'
      env: TOXENV=pypy
  # Added power support architecture
    - arch: ppc64le
      python: '3.6'
      env: TOXENV=docs
    - arch: ppc64le
      python: '3.6'
      env: TOXENV=flake8
    - arch: ppc64le
      python: '2.7'
      env: TOXENV=py27
    - arch: ppc64le
      python: '3.5'
      env: TOXENV=py35
    - arch: ppc64le
      python: '3.6'
      env: TOXENV=py36
    - arch: ppc64le
      python: '3.7'
      env: TOXENV=py37
    - arch: ppc64le
      python: '3.8'
      env: TOXENV=py38
    - arch: ppc64le
      python: '3.9-dev'
      env: TOXENV=py39

cache:
  directories:
    - $HOME/.wheels

# command to install dependencies, e.g. pip install -r requirements.txt
install:
  - mkdir -p $PIP_WHEEL_DIR
  - pip wheel -r _python_utils_tests/requirements.txt
  - pip install -e .
  - pip install tox

script:
  - tox

after_success:
  - pip install codecov coveralls
  - coveralls
  - codecov

notifications:
  email:
    on_success: never
    on_failure: change

