
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-16T12:55:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d9d24ef4dfabe8e3875936e561ee13768de640b",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
