
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-05T08:34:52-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "333108143a1f4b63d9fcd9842dbe35457025c180",
 "version": "0.0.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
