
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-12T11:19:17+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "716b2e6f0b326d2cd0afdba56b91dea6417e8138",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
