
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-11T16:19:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9efb9a4363c62b6a30c54b3b8e19c194f6516e7",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
