[tool.poetry]
name = "byroapi"
version = "0.2.1"
description = "REST API service for filling in and signig forms."
authors = ["Josef Nevrly <josef.nevrly@gmail.com>"]
license = "MIT license"

readme = "README.rst"

repository = "https://github.com/JNevrly/byroapi"

documentation = "https://github.com/JNevrly/byroapi"

homepage = "https://github.com/JNevrly/byroapi"

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10"
]

[tool.poetry.dependencies]
# List project dependencies here
python = "^3.8.0"
click = "^8.0.1"
onacol = "^0.3.0"
aiohttp = "^3.7.4"
PyPDF2 = "^1.26.0"
reportlab = "^3.6.5"
aioyagmail = "^0.0.4"
PyYAML = "^6.0"


[tool.poetry.scripts]
byroapi = "byroapi.cli:main"


[tool.poetry.dev-dependencies]
bump2version = "^0.5.0"
pip = "^18.1"
wheel = "^0.32.1"
watchdog = "^0.9.0"
flake8 = "^3.5.0"
tox = "^3.5.2"
coverage = {extras = ["toml"], version = "^5.5"}
Sphinx = "^4.1.1"
sphinx-rtd-theme = "^0.5.2"
twine = "^3.4.2"

setuptools = "^40.5.0"
rstcheck = "^3.3.1"
ptpython = "^2.0.4"
mypy = "^0.910"
jupyter = "^1.0.0"

[tool.coverage.run]
omit = [".*", "*/site-packages/*"]
source = ["byroapi"]
relative_files = true

[tool.coverage.report]
fail_under = 100
