[tool.poetry]
name = "cjolowicz-scripts"
version = "2022.1.9"
description = "Miscellaneous Python scripts"
authors = ["Claudio Jolowicz <mail@claudiojolowicz.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/cjolowicz/python-scripts"
repository = "https://github.com/cjolowicz/python-scripts"
documentation = "https://cjolowicz-scripts.readthedocs.io"
classifiers = [
    "Development Status :: 4 - Beta",
]

[tool.poetry.urls]
Changelog = "https://github.com/cjolowicz/python-scripts/releases"

[tool.poetry.dependencies]
python = ">=3.10"
click = ">=8.0.1"
platformdirs = ">=2.4.0"
httpx = ">=0.21.1"
rich = ">=10.15.2"
matplotlib = ">=3.5.0"
"github3.py" = ">=3.0.0"
Pygments = ">=2.10.0"
PyYAML = ">=6.0"

[tool.poetry.dev-dependencies]
pytest = ">=6.2.5"
coverage = {extras = ["toml"], version = ">=6.2"}
safety = ">=1.10.3"
mypy = ">=0.910"
typeguard = ">=2.13.2"
xdoctest = {extras = ["colors"], version = ">=0.15.10"}
sphinx = ">=4.3.1"
sphinx-autobuild = ">=2021.3.14"
pre-commit = ">=2.16.0"
flake8 = ">=4.0.1"
black = ">=21.10b0"
flake8-bandit = ">=2.1.2"
flake8-bugbear = ">=21.9.2"
flake8-docstrings = ">=1.6.0"
flake8-rst-docstrings = ">=0.2.3"
pep8-naming = ">=0.12.1"
darglint = ">=1.8.1"
reorder-python-imports = ">=2.6.0"
pre-commit-hooks = ">=4.0.1"
sphinx-click = ">=3.0.2"
Pygments = ">=2.10.0"
pyupgrade = ">=2.29.1"
furo = ">=2021.11.12"
sphinx-argparse = ">=0.3.1"
types-PyYAML = ">=6.0.1"

[tool.poetry.scripts]
stardate = "cjolowicz_scripts.stardate:main"
dependabot-rebase-all = "cjolowicz_scripts.dependabot_rebase_all:main"
mbox2maildir = "cjolowicz_scripts.mbox2maildir:main"
python-stdlib = "cjolowicz_scripts.python_stdlib:main"
compare-tools = "cjolowicz_scripts.compare_tools:main"
yaml2json = "cjolowicz_scripts.yaml2json:main"
pypi-dependents = "cjolowicz_scripts.pypi_dependents:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["cjolowicz_scripts", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 0

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[[tool.mypy.overrides]]
module = [
    "github3.*",
    "matplotlib.*",
    "pygments.*",
]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
