[tool.poetry]
name = "exmachina"
version = "0.0.3"
description = "botを作るためのフレームワークです"
authors = ["agarichan"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/agarichan/exmachina"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.71.0"

[tool.poetry.dev-dependencies]
tox = "^3.24.5"
ipykernel = "^6.6.1"
black = "^21.12b0"
flake8 = "^4.0.1"
isort = "^5.10.1"
tox-asdf = "^0.1.0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
poethepoet = "^0.12.0"
pyright = "^0.0.13"

[tool.poetry-dynamic-versioning]
enable = false
style = "pep440"

[tool.poetry-dynamic-versioning.substitution]
files = ["src/*/__init__.py"]

[tool.poe.tasks]
fmt = { shell = "isort src tests; black src tests" }
lint = { shell = "flake8 src tests && pyright src tests" }
test = { shell = "pytest && rm .coverage" }

[tool.black]
line-length = 120
exclude = '''
(
    .mypy_cache
    | .pytest_cache
    | .tox
    | .venv
    | dist
)
'''

[tool.isort]
line_length = 120
profile = "black"

[tool.pyright]
pythonVersion = "3.8"

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report term --cov-report xml"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
