
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T06:04:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9fd03c35308cdd844e4335cdade13f8acb1ccd34",
 "version": "1.16.0.post.dev77"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
