name: pygeohydro-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  # async_retriever
  - aiodns
  - aiohttp
  - aiohttp-client-cache>=0.5.1
  - aiosqlite
  - brotlipy
  - cchardet
  - cytoolz
  - importlib_metadata
  - ujson

  # pygeoogc deps
  - defusedxml
  - owslib
  - pydantic
  - pyyaml
  - pyproj>=1.2
  - requests
  - requests-cache>=0.8
  - shapely
  - urllib3

  # pygeoutils deps
  - dask-core
  - geopandas>=0.8
  - netcdf4
  - numpy>=1.17
  - rasterio>=1.2
  - xarray>=0.18

  # pynhd deps
  - networkx>=2.5
  - pandas>=1.0
  - pyarrow

  # pygeohydro deps
  - folium
  - lxml
  - matplotlib-base>=3.0
  - scipy

  # deps to speed up xarray and geopandas
  - pygeos
  - bottleneck

  # test deps
  - psutil
  - pytest-cov
  - pytest-xdist

  - pip
  - pip:
    - git+https://github.com/cheginit/async_retriever.git
    - git+https://github.com/cheginit/pygeoogc.git
    - git+https://github.com/cheginit/pygeoutils.git
    - git+https://github.com/cheginit/pynhd.git
