[tool.poetry]
name = "aoricaan-cli"
version = "0.1.12"
description = ""
authors = ["carlos <carlosaarivera23@gmail.com>"]
readme = 'README.md'

[tool.poetry.scripts]
apm = 'aoricaan_cli.cli:app'

[tool.poetry.dependencies]
python = "^3.8"
typer = {extras = ["all"], version = "^0.4.0"}
python-dotenv = "^0.19.1"
pydantic = "^1.8.2"
tqdm = "^4.62.3"
click-spinner = "^0.1.10"
tabulate = "^0.8.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
