
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-11T12:54:23+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "eef24e7b2d37b8b0acf0d223fcbcab5578cb469c",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
