[tool.poetry]
name = "akerbp.models"
version = "0.1.0"
description = "\"Machine Learning Models for Petrophysics\""
authors = ["Alfonso M. Canterla <alfonso.canterla@soprasteria.com>"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
readme = "README.md"
packages = [
    { include = "akerbp/models", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
xgboost = "1.3.3"
joblib = "1.0.1"
numpy = ">=1.19.5"
pandas = ">=1.3.2"
scikit-learn = ">=0.24.2"
pyod = "^0.9.7"
"akerbp.mlpet" = { path = "../akerbp-mlpet/", develop = true }

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = "^21.12b0"
ipython = "^7.31.0"
twine = "^3.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
