__title__ = 'xmind2testcase_xls'
__description__ = 'XMind2TestCase基于Python实现，提供了一个高效测试用例设计的解决方案！'
# __keywords__ = 'xmind2testCase, testcase, test, testing, xmind, 思维导图, XMind思维导图',
__url__ = 'https://github.com/zhuifengshen/xmind2testcase'
__author__ = 'krislzz'
__author_email__ = '710129642@qq.com'
__version__ = '0.0.4'
__license__ = 'MIT'
__cake__ = u'\u2728 \U0001f370 \u2728'
