[tool.poetry]
name = "offlinemsmtp"
version = "0.3.9"
description = "msmtp wrapper allowing for offline use"
authors = ["Sumner Evans <inquiries@sumnerevans.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://sr.ht/~sumner/offlinemsmtp"
keywords = ["email", "msmtp", "offline"]
classifiers = [
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    "Development Status :: 3 - Alpha",

    # Indicate who your project is intended for
    "Intended Audience :: End Users/Desktop",
    "Operating System :: POSIX",
    "Topic :: Communications :: Email :: Mail Transport Agents",
]

[tool.poetry.scripts]
offlinemsmtp = "offlinemsmtp.__main__:main"

[tool.poetry.urls]
"Bug Tracker" = "https://todo.sr.ht/~sumner/offlinemsmtp"

[tool.poetry.dependencies]
python = "^3.8"
PyGObject = "^3.38.0"
watchdog = "^0.10.3"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
docutils = "^0.16"
flake8 = "^3.8.3"
flake8-pep3101 = "^1.3.0"
jedi = "^0.17.2"
mypy = "^0.782"
rope = "^0.17.0"
rst2html5 = "^1.10.6"
sphinx = "^3.2.1"
termcolor = "^1.1.0"
twine = "^3.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
