[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)-8s] - %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%H:%M:%S"