# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\test-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2022-01-11 16:04:47.844805
__version__ = '3.2.5rc1'