[tool.poetry]
name = "pyridy"
version = "0.6.4"
description = "Support library for measurements made with the Ridy Android App"
authors = ["Philipp Simon Leibner <philipp.leibner@ifs.rwth-aachen.de>"]
license = "Apache-2.0"
readme = "README.md"

classifiers = [
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Intended Audience :: Science/Research"
]

keywords = ["signal processing", "ridy", "android"]

include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7.1, <3.11"
pytest = "^6.2.3"
numpy = "^1.20.2"
requests = "^2.25.1"
pandas = "^1.2.4"
matplotlib = "^3.4.1"
tqdm = "^4.60.0"
overpy = "^0.6"
geopy = "^2.1.0"
scipy = "^1.6.3"
pyproj = "^3.0.1"
ipyleaflet = "^0.15.0"
Sphinx = "^4.2.0"
sphinx-rtd-theme = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
