[tool.poetry]
name = "httpget"
version = "1.1.0"
description = "Download files using http"
authors = ["Wissem Mansouri <wissem.mansouri.ing@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"
tqdm = "^4.62.3"
flake8 = "^4.0.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
isort = "^5.10.1"
autopep8 = "^1.6.0"
yapf = "^0.32.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
