
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-10T19:28:35-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "30daa2556b7dc0d9ddf65fc0891ad4df2fb53108",
 "version": "0.0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
