
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-09T14:18:01-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "c38a9a8741c08fcb551dcdc81d8d1e428ab3dcde",
 "version": "1.6.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
