[build-system]
requires = [
    'param >=1.6.1',
    'pyct >= 0.4.8',
    'setuptools >= 54.1.2',
    'wheel >= 0.36.2',
]
[tool.check-manifest]
ignore = [
    'xrspatial/examples/*',
    'xrspatial/examples/user_guide/*',
    'xrspatial/.version',
]