[tool.poetry]
name = "pytest-timestamps"
version = "0.1.0"
description = "A simple plugin to view timestamps for each test"
authors = ["TJ <tbruno25@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pytest = "^5.2"

[tool.poetry.plugins."pytest11"]
timestamps = "pytest_timestamps.plugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
