
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-17T13:01:46-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9edb371503cc53b71628e4910eab7c4f92d181ae",
 "version": "0.5.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
