[tool.poetry]
name = "pqrs"
version = "0.4.0"
description = "CLI tool to manage Linux workstations."
authors = ["ProteinQure team <team@proteinqure.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
typer = "^0.3.2"
plumbum = "^1.7.0"
datafiles = "^0.15"
temppathlib = "^1.1.0"
semantic-version = "^2.8.5"
ansible = "^3.2.0"
ansible-runner = "^1.4.7"
pq-npyscreen = "^4.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pqrs = 'pqrs.cli:run'
