[tool.poetry]
name = "nonebot-plugin-setu-now"
version = "0.0.4.2"
description = "另一个色图插件"
authors = ["kexue"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
httpx = ">=0.18.0,<1.0.0"
webdav4 = "^0.9.3"
nonebot-adapter-cqhttp = "^2.0.0-alpha.16"

[tool.poetry.dev-dependencies]
nonebot2 = "2.0.0a16"
black = {version = "^21.12b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
