[tool.poetry]
name = "qfp"
version = "0.2.0"
description = "Quad-based audio fingerprinting (fork of https://github.com/mbortnyck/qfp)"
authors = [
	"Michael Bortnyck <michael.bortnyck@gmail.com>"
]
maintainers = [
	"Kyle Anthony Williams <kyle.anthony.williams2@gmail.com>"
]
readme = "README.md"
homepage = "https://github.com/SuperSonicHub1/qfp"
repository = "https://github.com/SuperSonicHub1/qfp"
documentation = "https://github.com/SuperSonicHub1/qfp#readme"
keywords = ['audio', 'fingerprinting']
classifiers = [
	"Topic :: Multimedia :: Sound/Audio :: Analysis"
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pydub = "^0.25.1"
numpy = "^1.22.1"
scipy = "^1.7.3"
bitstring = "^3.1.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
