
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-10T15:31:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5bdb09ed06b2892312d8f30c1656f6730d61c7e7",
 "version": "2022.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
