[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
python_functions = "test* should* given*"

[tool.poetry]
name = "f4ratk"
version = "2022.1"
description = "A Fama/French Finance Factor Regression Analysis Toolkit."
license = "AGPL-3.0-only"
authors = ["Tobias Röttger <dev@roettger-it.de>"]
readme = "README.md"
packages = [
    { include = "f4ratk" },
    { include = "COPYING", format = "sdist" },
]
homepage = "https://codeberg.org/toroettg/f4ratk"
repository = "https://codeberg.org/toroettg/f4ratk"
keywords = ["finance", "fama", "regression"]
classifiers = [
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Office/Business :: Financial",
    "Topic :: Utilities",
    "Development Status :: 4 - Beta",
    "Operating System :: OS Independent",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Financial and Insurance Industry",
    "Natural Language :: English",
    "Typing :: Typed"
]

[tool.poetry.urls]
"Issue Tracker" = "https://codeberg.org/toroettg/f4ratk/issues"
"Source Code" = "https://codeberg.org/toroettg/f4ratk"
"Donate" = "https://liberapay.com/f4ratk/donate"

[tool.poetry.scripts]
f4ratk = "f4ratk.cli.commands:main"
f4ratk-server = "f4ratk.web.server:main"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
importlib_metadata = "4.10.0"
appdirs = "1.4.4"
pandas = "1.3.5"
pandas-datareader = "0.10.0"
requests-cache = "0.9.0"
statsmodels = "0.13.1"
click = "8.0.3"
xlrd = "2.0.1"
PyYAML = "6.0"
flask = { version = "2.0.2", optional = true }
flask-caching = { version = "1.10.1", optional = true }
marshmallow = { version = "3.14.1", optional = true }
gunicorn  = { version = "20.1.0", optional = true }

scipy = "1.7.3"

[tool.poetry.extras]
server = ["flask", "flask-caching", "marshmallow"]
server-engine = ["gunicorn"]

[tool.poetry.dev-dependencies]
pytest = "6.2.5"
pytest-mock = "3.6.1"
pytest-cov = "3.0.0"
flake8 = "4.0.1"
flake8-isort = "4.1.1"
flake8-black = "0.2.3"
pyproject-flake8 = "0.0.1a2"
black = "21.12b0"

[tool.isort]
profile = "black"
combine_as_imports = true

[tool.black]
skip-string-normalization = true

[tool.flake8]
max-line-length = 88
extend-ignore = "E203, W503"
