
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-10T12:51:48+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "abf5881aa67412e4a243b13a59528a3c80aa2f52",
 "version": "v1.2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
