[tool.poetry]
name = "monobank_handler"
version = "0.1.7"
description = "Monobank.ua API implementation with handlers(poll/webhook)"
readme = "README.md"
homepage = "https://github.com/bezumnui/monobank_handler"
authors = ["George Viznyuk - (bezumnui)"]


[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.22"
ecdsa = "^0.13.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["flask>=2.0.0", "poetry>=0.12", "ecdsa>= 0.17.0", 'waitress>=2.0.0']
build-backend = "poetry.masonry.api"
