name: pygeoogc-tests
channels:
  - conda-forge
  - nodefaults
dependencies:
  # async_retriever
  - aiodns
  - aiohttp
  - aiohttp-client-cache>=0.5.1
  - aiosqlite
  - brotlipy
  - cchardet
  - cytoolz
  - importlib_metadata
  - ujson

  # pygeoogc deps
  - defusedxml
  - owslib
  - pydantic
  - pyyaml
  - pyproj>=1.2
  - requests
  - requests-cache>=0.8
  - shapely
  - urllib3

  # test deps
  - pandas
  - pytest-cov
  - pytest-xdist
  - psutil

  - pip
  - pip:
    - git+https://github.com/cheginit/async_retriever.git
