
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-12T16:02:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ffcb0271d0657c9ffa4fc01bebfb7d3851b3df79",
 "version": "0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
