apiVersion: v1
kind: PhJob
metadata:
  name: $name
  description: "pharbers job description"
  labels:
    name: $name
    runtime: $runtime
spec:
  containers:
    repository: local
    runtime: $runtime
    code: $code
    config: phconf.yaml
    args:
      - key: a
        value: 123
      - key: b
        value: 456
    outputs:
      - key: c
        value: abcde
      - key: d
        value: 6789


