# Configuration

site_name: Text Datasets
repo_url: https://github.com/bpiwowar/datamaestro_text

# Main pages
nav:
  - Home: index.md
  - API:
    - General: api.md
    - Information Retrieval: api/ir.md


# Automatic page generation for datasets
plugins:
  - datamaestro:
      repository: text
  - experimaestro:
      modules:
        - datamaestro_text.data.ir: api/ir.md
        - datamaestro_text: api.md
  - search

# Theme
theme:
    name: readthedocs
    highlightjs: true
    collapse_navigation: true
