[tool.poetry]
name = "cells"
version = "0.1.1a3"
description = ""
authors = ["Darren Burns <darren@textualize.io>"]

[tool.poetry.dependencies]
python = "^3.6.2"
pytest-cov = "^3.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.12b0"
mypy = "^0.931"
pre-commit = "^2.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
