[tool.poetry]
name = "impartial"
version = "0.2.0"
description = "A lightweight extension of functools.partial"
authors = ["Georg Wölflein <georgw7777@gmail.com>"]
license = "Apache-2.0"
packages = [
    { include = "impartial" }
]
readme = "README.md"
repository = "https://github.com/georg-wolflein/impartial"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
python = "^3.7"
typing-extensions = "^4.0.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
