variables_to_rename:
  'Chance of Admit ': Admit
  'LOR ': LOR
  'GRE Score': GRE
  'TOEFL Score': TOEFL
  'University Rating': Rating

columns_to_drop:
  - Serial No.

pipeline_save_file: admission_model_output_v

SEED : 0
TARGET : 'Admit'

PREDICTORS:
  - 'GRE'
  - 'TOEFL'
  - 'Rating'
  - 'SOP'
  - 'LOR'
  - 'CGPA'
  - 'Research'

PREDICTORS_DISCRETE:
  - 'University Rating'
  - 'SOP'
  - 'LOR'
  - 'Research'

PREDICTOR_MAPPING: 
  1.0 : 1
  1.5 : 2
  2.0: 3
  2.5: 4
  3.0: 5
  3.5: 6
  4.0: 7
  4.5: 8
  5.0: 9

PREDICTORS_TO_MAP: 
  - 'SOP'
  - 'LOR'

PREDICTORS_LOG_TRANSFORM:
  - 'GRE'
  - 'TOEFL'

PREDICTORS_YEO_TRANSFORM:
  - 'CGPA'

training_data_file : 'Admission_Predict.csv'
test_size : 0.2