
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-15T16:44:00-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3f5631033c2e4a813a98723a5915c121db2232f",
 "version": "2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
