[tool.poetry]
name = "ml_init"
version = "0.2.0"
description = "Install the main ML libraries"
authors = ["Alberto Rubiales <al.rubiales.b@gmail.com>"]
readme = "README.md"
homepage = ""
license = "MIT"

[tool.poetry.dependencies]
python = "3.9"
llvmlite = "^0.38.0"
bertopic = "^0.9.4"
scikit-learn = "^1.0.2"
torch = "^1.10.1"
transformers = "^4.15.0"
matplotlib = "^3.5.1"
seaborn = "^0.11.2"
scipy = "^1.7.3"
optuna = "^2.10.0"
mlflow = "^1.22.0"
flake8 = "^4.0.1"
jupyter = "^1.0.0"
notebook = "^6.4.7"
black = "^21.12b0"
xgboost = "^1.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
