VERSION_YEAR = 2022
VERSION_MONTH = int('01')
VERSION_DAY = int('13')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('54')
MAJOR_VERSION = 1
MINOR_VERSION = 3
PATCH_VERSION = 202201131054
version_date = '2022/01/13 10:54'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
