VERSION_YEAR = 2022
VERSION_MONTH = int('01')
VERSION_DAY = int('12')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('45')
MAJOR_VERSION = 1
MINOR_VERSION = 3
PATCH_VERSION = 202201121645
version_date = '2022/01/12 16:45'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
