
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-13T19:26:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2d0034dd731c683f97873fae643ac3d3cac3d47",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
