
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T04:49:06+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddb3bcab074ef6241ee64dd8b1871bca4d5ed6a0",
 "version": "2.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
