from typing import Optional, Tuple, List

ResolvedType = Optional[Tuple[int, List[Tuple[str, str]]]]


class Router:
    def add_validator(self, alias: str, regex: str) -> None: ...

    def add_route(self, method: str, path: str, handler_id: int) -> None: ...

    def add_location(self, method: str, path: str, handler_id: int) -> None: ...

    def resolve(self, method: str, path: str) -> ResolvedType: ...

    def set_ignore_trailing_slashes(self) -> None: ...
