[tool.poetry]
name = "cloops"
version = "0.0.4"
description = "dfsdfsdfsdf"
authors = ["Your Name <you@example.com>"]
license = "fsdfsdsdf"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
