
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-13T11:38:26-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d30544bed54c1972359dd261874c5ef47cbedb3",
 "version": "0.5.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
