[tool.poetry]
name = "gtfs_kit"
version = "5.2.0"
description = "A Python 3.7+ library for analyzing GTFS feeds."
authors = ["Alex Raichev <araichev@mrcagney.com>"]
readme = "README.rst"
license = "MIT"
repository = "https://github.com/mrcagney/gtfs_kit"
documentation = "https://mrcagney.github.io/gtfs_kit_docs"
exclude = ["tests", "docs"]

[tool.poetry.dependencies]
python = "^3.7 || ^3.8 || ^3.9"
pandas = "<2"
shapely = "<2"
pycountry = "<20"
utm = "<1"
json2html = "<2"
geopandas = "<1"
rtree = "< 1"
folium = "<1"
requests = "<3"

[tool.poetry.dev-dependencies]
jupyter = "*"
pytest = "<7"
sphinx = "<4"
pre-commit = "*"
black = "=19.3b0"
publish_sphinx_docs = "^1.0"
matplotlib = "*"
pytest-socket = "*"
nbstripout = "^0.4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

