
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-11T11:08:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf6a9e72f335e909a204d005c8ef6de958c0b311",
 "version": "0.7.1.post.dev295"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
