
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-10T14:52:07-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "14aa1ab5e8ae72d75a2f1094d4a9f4626f74f214",
 "version": "v2.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
