[tool.poetry]
name = "az-cp-dummy"
version = "0.1.0"
description = "A dummy package to test pip & similar"
authors = ["Francesco Pasa <francesco.pasa@astrazeneca.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
