from VCIBD2 import takeCommand

def  VC2():
    print("Tell me the operation you want to do. addition, substraction, multiplication or division.")
    takeCommand.speak("Tell me the operation you want to do. addition, substraction, multiplication or division.")
    operation = takeCommand.takeCommand()

#-----------------------------------------------------------------------------------------------------------------------------------
    if operation=="addition":
        print("tell the two numbers you want to add.")
        takeCommand.speak("tell the two numbers you want to add.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        AF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        AS = int(takeCommand.takeCommand())
        S = (AF+AS)
        print(f"The sum is : {S}")
        takeCommand.speak(f"The sum is : {S}")
    if operation=="addison":
        print("tell the two numbers you want to add.")
        takeCommand.speak("tell the two numbers you want to add.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        AF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        AS = int(takeCommand.takeCommand())
        S = (AF+AS)
        print(f"The sum is : {S}")
        takeCommand.speak(f"The sum is : {S}")
    if operation=="Addison":
        print("tell the two numbers you want to add.")
        takeCommand.speak("tell the two numbers you want to add.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        AF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        AS = int(takeCommand.takeCommand())
        S = (AF+AS)
        print(f"The sum is : {S}")
        takeCommand.speak(f"The sum is : {S}")
    if operation=="ad":
        print("tell the two numbers you want to add.")
        takeCommand.speak("tell the two numbers you want to add.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        AF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        AS = int(takeCommand.takeCommand())
        S = (AF+AS)
        print(f"The sum is : {S}")
        takeCommand.speak(f"The sum is : {S}")
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    if operation=="substraction":
        print("tell the two numbers you want to substract.")
        takeCommand.speak("tell the two numbers you want to substract.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        SF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        SS = int(takeCommand.takeCommand())
        D = (SF-SS)
        print(f"The diffrence is : {D}")
        takeCommand.speak(f"The diffrence is : {D}")
    if operation=="substract":
        print("tell the two numbers you want to substract.")
        takeCommand.speak("tell the two numbers you want to substract.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        SF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        SS = int(takeCommand.takeCommand())
        D = (SF-SS)
        print(f"The diffrence is : {D}")
        takeCommand.speak(f"The diffrence is : {D}")
    if operation=="subtraction":
        print("tell the two numbers you want to substract.")
        takeCommand.speak("tell the two numbers you want to substract.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        SF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        SS = int(takeCommand.takeCommand())
        D = (SF-SS)
        print(f"The diffrence is : {D}")
        takeCommand.speak(f"The diffrence is : {D}")
    if operation=="traction":
        print("tell the two numbers you want to substract.")
        takeCommand.speak("tell the two numbers you want to substract.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        SF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        SS = int(takeCommand.takeCommand())
        D = (SF-SS)
        print(f"The diffrence is : {D}")
        takeCommand.speak(f"The diffrence is : {D}")
#---------------------------------------------------------------------------------------------------------------

    if operation=="multiplication":
        print("tell the two numbers you want to multiply.")
        takeCommand.speak("tell the two numbers you want to multiply.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        MF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        MS = int(takeCommand.takeCommand())
        P = (MF*MS)
        print(f"The product is : {P}")
        takeCommand.speak(f"The product is : {P}")
    if operation=="multiply":
        print("tell the two numbers you want to multiply.")
        takeCommand.speak("tell the two numbers you want to multiply.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        MF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        MS = int(takeCommand.takeCommand())
        P = (MF*MS)
        print(f"The product is : {P}")
        takeCommand.speak(f"The product is : {P}")
#-------------------------------------------------------------------------------------------------------------

    if operation=="division":
        print("tell the two numbers you want to divide.")
        takeCommand.speak("tell the two numbers you want to divide.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        DF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        DS = int(takeCommand.takeCommand())
        Q = (DF/DS)
        print(f"The quotient is : {Q}")
        takeCommand.speak(f"The quotient is : {Q}")
    if operation=="divide":
        print("tell the two numbers you want to divide.")
        takeCommand.speak("tell the two numbers you want to divide.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        DF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        DS = int(takeCommand.takeCommand())
        Q = (DF/DS)
        print(f"The quotient is : {Q}")
        takeCommand.speak(f"The quotient is : {Q}")
    if operation=="divid":
        print("tell the two numbers you want to divide.")
        takeCommand.speak("tell the two numbers you want to divide.")
        print("tell the first number : ")
        takeCommand.speak("tell the first number : ")
        DF = int(takeCommand.takeCommand())
        print("tell the second number : ")
        takeCommand.speak("tell the second number : ")
        DS = int(takeCommand.takeCommand())
        Q = (DF/DS)
        print(f"The quotient is : {Q}")
        takeCommand.speak(f"The quotient is : {Q}")

VC2()