[project]
requires-python = ">=3.6"

[build-system]
requires = [
	"setuptools>=42",
	"wheel",
	"cython",
	"versioningit ~= 0.3.0"
	]
build-backend = "setuptools.build_meta"

[tool.versioningit.vcs]
default-tag = "v0.0.0"

[tool.versioningit.tag2version]
rmprefix = "postcompiler_"  # For old tags

[tool.versioningit.format]
distance = "{version}.dev_{distance}+{rev}"
dirty = "{version}+dirty_{build_date:%Y.%m.%d}"
distance-dirty = "{version}.dev{distance}+{rev}.dirty_{build_date:%Y.%m.%d}"

[tool.versioningit.write]
method = "basic"
file = "src/srctools/_version.py"

[tool.pyright]
include = [
	"src/srctools/"
	]
exclude = [
	# Tests deliberately do incorrect things to test error handling, so ignore types.
	"tests/",
	"**/__pycache__"
	]
# We want to do conversions when setting.
reportPropertyTypeMismatch = false
