[package]
name = "aliyundrive-webdav"
version = "1.1.1"
edition = "2021"
description = "WebDAV server for AliyunDrive"
license = "MIT"
homepage = "https://github.com/messense/aliyundrive-webdav"
repository = "https://github.com/messense/aliyundrive-webdav.git"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
bytes = "1.0.1"
clap = { version = "3.0.1", features = ["derive", "env", "wrap_help"] }
dashmap = "5.0.0"
futures-util = "0.3"
headers = "0.3.4"
hyper = { version = "0.14.11", features = ["server"] }
moka = { version = "0.7.1", default-features = false, features = ["future"] }
openssl-probe = { version = "0.1.4", optional = true }
reqwest = { version = "0.11.7", default-features = false, features = ["json", "gzip"] }
serde = { version = "1.0.127", features = ["derive"] }
time = { version = "0.3", features = ["formatting", "parsing"] }
tokio = { version = "1.10.0", features = ["rt-multi-thread", "io-util", "net", "time", "sync", "macros", "parking_lot", "fs"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "local-time"] }
url = "2.2.2"
dav-server = { version = "0.3.0", default-features = false, features = ["hyper"] }

[features]
default = ["rustls-tls", "atomic64"]
rustls-tls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]
native-tls-vendored = ["reqwest/native-tls-vendored", "openssl-probe"]
atomic64 = ["moka/atomic64"]

[profile.release]
lto = true
opt-level = "z"  # Optimize for size
