
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T16:44:55+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "007fb89a7f0ad257b4f46b9d55a73bcd7cd404e5",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
