[dependencies.opaquebind_core]
path = "local_dependencies/opaquebind_core"

[dependencies.pyo3]
features = ["extension-module"]
version = "~0.14"

[lib]
crate-type = ["cdylib"]
name = "opaquepy"

[package]
edition = "2021"
name = "opaquepy"
version = "0.1.7"
[package.metadata.maturin]
python-source = "python"
