[tool.poetry]
name = "flox-git"
version = "0.1.2"
homepage = "https://github.com/getflox/flox-git"
description = "Bootstrap git repository for your project managed by flox."
authors = ["Michal Przytulski <michal@przytulski.pl>", "Daniel Ancuta <whisller@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.2"
GitPython = "^3.1.0"
flox-core = ">=0.2,<1.0.0"

[tool.poetry.dev-dependencies]
bump2version = "^1.0.1"

[tool.poetry.plugins."flox.plugin"]
git = "flox_git:plugin"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
