
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "48cee122d5979df959a62705afe8ff9b4ca2a237",
 "version": "7.6.3pre1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
