
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-10T01:49:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c1a1aecbcdb1e76814db5fc131b18c3f1a20ca1",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
