[tool.poetry]
name = "start-django-project"
version = "1.0.0"
readme = "README.md"
description = "Init a new django project with a simple bootstrap layout"
authors = ["TechHeart <contact@TechHeart.co.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start-django-project = 'start-django-project.cli:cli'
