[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[project]
name = "gidapptools"
authors = [{ name = "brocaprogs" }]
classifiers = ["License :: OSI Approved :: MIT License"]
license = { file = "LICENSE" }
readme = "README.md"
dynamic = ['version', 'description']
requires-python = ">=3.9"
dependencies = [
    "appdirs",
    "psutil",
    "urlextract",
    "yarl",
    "tzlocal",
    "PySide6>=6.2.2",
    "pytz",
    "inflect",
    "orjson",
    "pyparsing>=3.0.6",
    "click",
    "pprintpp",
    "pp-ez",
    "tzlocal>=4.1",
    "python-dateutil",
    "attrs>=21.2.0",
    "rich>=10.12.0",
    "sortedcontainers>=2.4.0",
    "py7zr"
]

[project.urls]
Source = "https://github.com/Giddius/GidAppTools"

[project.scripts]
appmeta = "gidapptools.__main__:appmeta_cli"

[project.optional-dependencies]

[tool.flit.sdist]
exclude = [
    "misc",
    "temp",
    "docs",
    "tools",
    ".pydeps",
    "tests",
    ".gitattributes",
    ".gitignore",
    ".editorconfig",
    "planning.todo",
    "tasks.py",
]

[tool.autopep8]
ignore = ["E402", "E501"]
max-line-length = 250

[tool.isort]
balanced_wrapping = true
ensure_newline_before_comments = true
group_by_package = true
import_heading_firstparty = "* Local Imports --------------------------------------------------------------------------------------->"
import_heading_gid = "* Gid Imports ----------------------------------------------------------------------------------------->"
import_heading_pyqt = "* PyQt5 Imports --------------------------------------------------------------------------------------->"
import_heading_stdlib = "* Standard Library Imports ---------------------------------------------------------------------------->"
import_heading_thirdparty = "* Third Party Imports --------------------------------------------------------------------------------->"
known_gid = [
    "gidtools",
    "gidlogger",
    "gidqtutils",
    "gidviewmodels",
    "gidapptools"
]
known_pyqt = ["PyQt5", "PySide6"]
length_sort = true
line_length = 200
lines_after_imports = 1
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "PYQT",
    "GID",
    "FIRSTPARTY",
    "LOCALFOLDER",
]

[tool.pytest.ini_options]
addopts = "-rA -vv --durations=0 --capture=tee-sys --show-capture=all --color=auto --code-highlight=yes"
