
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-11T16:23:31-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "22d921efde01db02e8fcfc5f0382df8cef66ae09",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
