[tool.poetry]
name = "tictactoelogic"
version = "0.1.3"
description = "Onboarding project phase 1"
authors = ["Alexandre Meneses <alexandre.meneses@fabamaq.com>"]
packages = [
    { include = "logic", from="src"},
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
