[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]

# build-system.requires gives a list of packages that are needed to build your package.
# Listing something here will only make it available during the build, not after it is installed.
build-backend = "setuptools.build_meta"