[tool.poetry]
name = "sign-off"
version = "0.1.0"
description = "pre-commit hook to add \"signed-off-by\" line to commit messages"
authors = ["dynobo <dynobo@mailbox.org>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/dynobo/sign-off"
keywords = ["pre-commit", "hook"]
classifiers = [
  "Topic :: Software Development",
  "Topic :: Software Development :: Version Control",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pytest = "^6.2.5"
mypy = "^0.931"
pylint = "^2.12.2"
isort = "^5.10.1"
pre-commit = "^2.16.0"
tbump = "^6.7.0"
pytest-cov = "^3.0.0"
coveralls = "^3.3.1"

[tool.poetry.scripts]
sign-off = "sign_off.sign_off:main"

[tool.pytest.ini_options]
addopts = "--cov sign_off --cov-report xml:cov.xml --cov-report html"
testpaths = ["tests"]

[tool.isort]
profile = "black"
multi_line_output = 4

[tool.pylint.'MESSAGES CONTROL']
disable = ["missing-function-docstring", "protected-access"]

[tool.tbump]
github_url = "https://github.com/dynobo/sign-off/"

[tool.tbump.version]
current = "0.1.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[tool.tbump.file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'

[[tool.tbump.file]]
src = "sign_off/__init__.py"
search = '__version__ = "{current_version}"'

[[tool.tbump.file]]
src = "README.md"
search = "rev: v{current_version}"

[[tool.tbump.before_commit]]
name = "check changelog"
cmd = "grep -q {new_version} CHANGELOG.md"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
