
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T02:25:48+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8958058993847815cfd12c1633d97fd43930ff3e",
 "version": "v0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
