openapi: "3.0.1"
info:
  title: "jsonapi-openapi-template"
  description: "jsonapi"
  version: "2020-06-02T10:27:38Z"
servers:
  - url: "https://2t69b7x032.execute-api.cn-northwest-1.amazonaws.com.cn/{basePath}"
    variables:
      basePath:
        default: "/v0"
paths:
  /{project_name}/{type}/{id}/{relationship}:
    get:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "relationship"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
    post:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "relationship"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
    delete:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "relationship"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
    patch:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "relationship"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
  /{project_name}/{type}/{id}/relationships/{relationship}:
    get:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "relationship"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
    post:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "relationship"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
    delete:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "relationship"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
    patch:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "relationship"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
  /{project_name}/{type}:
    get:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
    post:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
  /{project_name}/{type}/{id}:
    get:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
    post:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
    delete:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
    patch:
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "Accept"
          in: "header"
          schema:
            type: "string"
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      security:
        - sigv4: []
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
  securitySchemes:
    sigv4:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "awsSigv4"
x-amazon-apigateway-policy:
  Version: "2012-10-17"
  Statement:
    - Effect: "Allow"
      Principal: "*"
      Action: "execute-api:Invoke"
      Resource: "arn:aws-cn:execute-api:cn-northwest-1:444603803904:2t69b7x032/*"

