
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-16T06:43:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "87a1ef834388468a29e4a689d2c12df638136206",
 "version": "2022.1.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
