[tool.poetry]
name = "mixologist"
version = "0.1.0"
description = ""
authors = ["David Francos <opensource@davidfrancos.net>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.70.1"
httpx = "^0.21.1"
uvicorn = "^0.16.0"
asyncio-mqtt = "^0.11.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
