ci:
    autoupdate_schedule: monthly
    autofix_prs: true

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.25.0
    hooks:
    - id: pyupgrade
      args: [--py37-plus]

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: '3.9.2'
    hooks:
    - id: flake8
      additional_dependencies:
      - flake8-bugbear==20.1.4
      - flake8-builtins==1.5.3
      - flake8-comprehensions==3.2.3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    - id: mypy
      files: ^(aiida_firecrest/.*py)$
      additional_dependencies:
      - "types-PyYAML"
