
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-14T13:08:01-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "acc0114f273fcde5e5a30bc71f5a0df5728654af",
 "version": "v0.2.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
