[tool.poetry]
name = "rearq"
version = "0.2.6"
description = "Rewrite arq and make improvement."
authors = ["long2ice <long2ice@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/long2ice/rearq.git"
repository = "https://github.com/long2ice/rearq.git"
documentation = "https://github.com/long2ice/rearq/blob/master/README.md"
keywords = ["asyncio", "task", "arq", "queue", "distributed"]
packages = [
    { include = "rearq" }
]
include = ["LICENSE", "README.md", "CHANGELOG.md"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "*"
click = "*"
aioredis = "*"
crontab = "*"
uvicorn = { version = "*", extras = ["standard"] }
fastapi = "*"
loguru = "*"
jinja2 = "*"
aiofiles = "*"
tortoise-orm = "^0.18.1"
asyncmy = { version = "*", optional = true }
asyncpg = { version = "*", optional = true }

[tool.poetry.dev-dependencies]
flake8 = "*"
isort = "*"
black = "*"
pytest = "*"
pytest-xdist = "*"
bandit = "*"
pytest-asyncio = "*"
cryptography = "*"

[tool.poetry.extras]
postgres = ["asyncpg"]
mysql = ["asyncmy"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
rearq = "rearq.cli:main"
