name: CICD

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  run-py-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions
          ref: feature/no-commit

      - name: Run tests
        uses: ./actions/py/test
        with:
          python-version: ${{ matrix.python-version }}
          unit-test-directory: tests/unit

  run-js-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions
          ref: feature/no-commit

      - name: Run tests
        uses: ./actions/js/test
        with:
          node-version: ${{ matrix.node-version }}

  publish-js:
    needs: [ run-py-tests, run-js-tests ]
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions
          ref: feature/no-commit

      - name: Publish release
        uses: ./actions/js/publish
        with:
          node-version: 12.21.x
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}

  publish-python:
    needs: publish-js
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout actions repository
        uses: actions/checkout@v2
        with:
          repository: Exabyte-io/actions
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          path: actions
          ref: feature/no-commit

      - name: Publish release
        uses: ./actions/py/publish
        with:
          python-version: 3.x
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          pypi-username: ${{ secrets.PYPI_USERNAME }}
          pypi-password: ${{ secrets.PYPI_PASSWORD }}
          publish-tag: 'false'
