
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-10T16:11:54-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "69dd3c14c513a8721e81dfb9fca14f7535c1c263",
 "version": "v2.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
