[tool.poetry]
name = "meta-weather-cli"
version = "0.1.6"
description = "A CLI to check weather in cities around the globe"
authors = ["Omer Ben David"]

[tool.poetry.scripts]
meta-weather-cli = 'meta_weather_cli:cli'

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
