[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "maritest"
authors = [{name = "Ryan Febriansyah", email = "ryanfebriansyah72@gmail.com"}]
dynamic = ["version", "description"]
