
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-16T02:20:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b944c485b0d128d0ccc0b7b90002625ff046b98b",
 "version": "0.4.dev2203"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
