
[tool.poetry]
name = "pkgreserved"
version = "0.0.1"
description = "Description"
authors = ["Reserver <reserving.package.name@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
