
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-10T19:38:27+0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "85326def3765f0668d3638fa479804fe804b5db4",
 "version": "2.3.4.dev20220111"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
