
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-13T12:26:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "96ae12d560480005682a34182429d82c21bcbcd6",
 "version": "0.1.1.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
