[tool.poetry]
name = "afsql"
version = "0.2.1"
description = ""
authors = ["Asdil"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
DBUtils = "^2.0"
neo4j = "^4.2.1"
py2neo = "2021.2.3"
PyMySQL = "^1.0.2"
psycopg2-binary = "^2.9.3"
redis = "^4.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
