
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-12T15:01:45-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "38c1941269c9b3d05d1ab37f629adcb2a55e5899",
 "version": "5.2.12.post0.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
