
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-13T16:10:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2637a3c32c93766a86650ae7ec3760e3f65a42ea",
 "version": "v0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
