[tool.poetry]
name = "tidy-twitter"
version = "1.1.0"
description = "tidy-twitter helps to clean up user's Twitter history."
authors = ["Sven Varkel <sven@wasabi.ee>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.3"
python-dateutil = "^2.8.2"
pytz = "^2021.3"
tqdm = "^4.62.3"
python-twitter = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tidy_twitter = "tidy_twitter.cli:cli"
