[tool.poetry]
name = "ah_blackjack"
version = "0.1.4"
description = "Black jack in terminal"
authors = ["Andrew Horbach <andrewhorbach@gmail.com>"]
keywords = ["python3", "ASCII", "game"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/karma-git/belhard_base_python"
repository = "https://github.com/karma-git/belhard_base_python"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6"
colorama = "^0.4.4"
names = "^0.3.0"


[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
bj = "ah_blackjack.main:main"
