[tool.poetry]
name = "simsapa"
version = "0.1.7.dev4"
description = "Simsapa Dhamma Reader"
authors = ["Gambhiro <gambhiro.bhikkhu.85@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
PyQt5 = "^5.15.4"
SQLAlchemy = "^1.4.6"
Markdown = "^3.3.4"
PyYAML = "^5.4.1"
SQLAlchemy-Utils = "^0.37.2"
requests = "^2.25.1"
appdirs = "^1.4.4"
PyPDF2 = "^1.26.0"
epub_meta = "^0.0.7"

PyMuPDF = [
  { version =  "^1.18.13", markers = "sys_platform == 'linux' and platform_machine == 'x86_64'" },
  { version =  "^1.18.13", platform = "win32" },
  { version =  "^1.18.13", platform = "darwin" },
]
pandas = "^1.2.4"
openpyxl = "^3.0.7"
semver = "^2.13.0"
pyglossary = "^4.0.11"
lxml = "^4.6.3"
python-dotenv = "^0.17.1"
pyperclip = "^1.8.2"
PyQtWebEngine = "^5.15.4"
networkx = "^2.5.1"
bokeh = "^2.3.2"
alembic = "^1.7.5"
sqlalchemy2-stubs = "^0.0.2-alpha.19"
python-idzip = "^0.3.7"
bleach = "^4.1.0"
Whoosh = "^2.7.4"
typer = "^0.4.0"
tomlkit = "^0.8.0"

pyqtkeybind = [
  { version = "^0.0.8", platform = "linux" },
]

# Importing from project folder directly.
# keyboard = [
#   { git = "https://github.com/boppreh/keyboard.git", rev = "51601e61df89af8e27e3604ce75b70dea726647c", platform = "win32" },
#   { git = "https://github.com/boppreh/keyboard.git", rev = "51601e61df89af8e27e3604ce75b70dea726647c", platform = "darwin" },
# ]

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pyArango = "^1.3.5"

[tool.poetry.scripts]
simsapa = 'simsapa.runner:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
