[tool.poetry]
name = "axiom-py"
version = "0.1.0-beta.4"
description = "Axiom API Python bindings."
authors = ["Axiom, Inc."]
license = "MIT"
packages = [
	{ include = "axiom" },
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
requests-toolbelt = "^0.9.1"
ujson = "^4.0.2"
dacite = "^1.6.0"
pyhumps = "^1.6.1"
ndjson = "^0.3.1"
rfc3339 = "^6.2"
iso8601 = "^1.0.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pytest = "^6.2.2"
pylint = "^2.7.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
