[tool.poetry]
name = "pprofiler"
version = "0.1.2"
description = "Python Decorator for Profiling Function or Method"
readme = "README.md"
homepage = "https://github.com/nsiregar/pprof"
repository = "https://github.com/nsiregar/pprof"
authors = ["Ngalim Siregar <ngalim.siregar@gmail.com>"]
license = "MIT"
classifiers = [
    "Environment :: Console",
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.8',
    'Topic :: Software Development :: Libraries :: Python Modules',
    "Topic :: Software Development :: Quality Assurance",
    'Topic :: Utilities',
]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
