
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-17T09:55:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1be7931a78522020b6d13c40b816f0f02dd09608",
 "version": "2022.01.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
