{% set name = "amdnet" %}
{% set version = "1.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amdnet-{{ version }}.tar.gz
  sha256: 55f2fb96a28be769d93a3c5ac08ecbc1669d188c5de3ea273bffa5ae6d65b716

build:
  number: 0
  noarch: python
  entry_points:
    - amdnet = train_AMDNet:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.6,<3.9
  run:
    - keras
    - python >=3.6,<3.9

test:
  imports:
    - amdnet
    - amdnet.layers
  commands:
    - pip check
    - amdnet --help
  requires:
    - pip

about:
  home: https://pypi.org/project/amdnet/
  summary: Structure motif-centric learning framework for inorganic crystalline systems.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgbaird
