[tool.poetry]
name = "jsw-nx"
version = "1.0.1"
description = "Next toolkit for python."
authors = ["feizheng <1290657123@qq.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
