[tool.poetry]
name = "views_dataviz"
version = "0.9.0"
description = ""
authors = ["peder2911 <pglandsverk@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
matplotlib = "^3.4.3"
pandas = "^1.3.2"
seaborn = "^0.11.2"
ipykernel = "^6.4.1"
contextily = "^1.1.0"
geopandas = "^0.9.0"
adjustText = "^0.7.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
