
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-14T11:19:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2dbd74fb3ddb3acb07f3ad3c03a2f2bd5c9901bd",
 "version": "0.7.1.post.dev297"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
