"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import nucliadb_protos.utils_pb2
import typing
import typing_extensions
from nucliadb_protos.utils_pb2 import (
    EntityRelation as EntityRelation,
    ExtractedText as ExtractedText,
    Relation as Relation,
    Vector as Vector,
    VectorObject as VectorObject,
    Vectors as Vectors,
)


DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class TextInformation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TEXT_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    text: typing.Text = ...
    @property
    def labels(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        text : typing.Text = ...,
        labels : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["labels",b"labels","text",b"text"]) -> None: ...
global___TextInformation = TextInformation

class Metadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ORIGIN_FIELD_NUMBER: builtins.int
    SLUG_FIELD_NUMBER: builtins.int
    MODIFIED_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    ICON_FIELD_NUMBER: builtins.int
    origin: typing.Text = ...
    """Tantivy doc & para faceted"""

    slug: typing.Text = ...
    """Tantivy doc & para"""

    @property
    def modified(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Tantivy doc & para"""
        pass
    @property
    def created(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Tantivy doc & para"""
        pass
    icon: typing.Text = ...
    """Tantivy doc & para faceted"""

    def __init__(self,
        *,
        origin : typing.Text = ...,
        slug : typing.Text = ...,
        modified : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        created : typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        icon : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["created",b"created","modified",b"modified"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["created",b"created","icon",b"icon","modified",b"modified","origin",b"origin","slug",b"slug"]) -> None: ...
global___Metadata = Metadata

class ShardId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    def __init__(self,
        *,
        id : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___ShardId = ShardId

class ResourceID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SHARD_ID_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    shard_id: typing.Text = ...
    uuid: typing.Text = ...
    def __init__(self,
        *,
        shard_id : typing.Text = ...,
        uuid : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["shard_id",b"shard_id","uuid",b"uuid"]) -> None: ...
global___ResourceID = ResourceID

class Shard(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SHARD_ID_FIELD_NUMBER: builtins.int
    RESOURCES_FIELD_NUMBER: builtins.int
    shard_id: typing.Text = ...
    resources: builtins.int = ...
    def __init__(self,
        *,
        shard_id : typing.Text = ...,
        resources : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["resources",b"resources","shard_id",b"shard_id"]) -> None: ...
global___Shard = Shard

class ShardList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SHARDS_FIELD_NUMBER: builtins.int
    @property
    def shards(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Shard]: ...
    def __init__(self,
        *,
        shards : typing.Optional[typing.Iterable[global___Shard]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["shards",b"shards"]) -> None: ...
global___ShardList = ShardList

class EmptyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___EmptyResponse = EmptyResponse

class EmptyQuery(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    def __init__(self,
        ) -> None: ...
global___EmptyQuery = EmptyQuery

class Paragraph(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class SentencesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        value: builtins.bytes = ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : builtins.bytes = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    SENTENCES_FIELD_NUMBER: builtins.int
    FIELD_FIELD_NUMBER: builtins.int
    start: builtins.int = ...
    """Start end position in field text"""

    end: builtins.int = ...
    """Start end position in field text"""

    @property
    def labels(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """Paragraph specific labels"""
        pass
    @property
    def sentences(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, builtins.bytes]:
        """key is full id for vectors"""
        pass
    field: typing.Text = ...
    def __init__(self,
        *,
        start : builtins.int = ...,
        end : builtins.int = ...,
        labels : typing.Optional[typing.Iterable[typing.Text]] = ...,
        sentences : typing.Optional[typing.Mapping[typing.Text, builtins.bytes]] = ...,
        field : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["end",b"end","field",b"field","labels",b"labels","sentences",b"sentences","start",b"start"]) -> None: ...
global___Paragraph = Paragraph

class Paragraphs(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class ParagraphsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        @property
        def value(self) -> global___Paragraph: ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Optional[global___Paragraph] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    PARAGRAPHS_FIELD_NUMBER: builtins.int
    @property
    def paragraphs(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___Paragraph]: ...
    def __init__(self,
        *,
        paragraphs : typing.Optional[typing.Mapping[typing.Text, global___Paragraph]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["paragraphs",b"paragraphs"]) -> None: ...
global___Paragraphs = Paragraphs

class Resource(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class ResourceStatus(_ResourceStatus, metaclass=_ResourceStatusEnumTypeWrapper):
        pass
    class _ResourceStatus:
        V = typing.NewType('V', builtins.int)
    class _ResourceStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResourceStatus.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        USEFUL = Resource.ResourceStatus.V(0)
        EMPTY = Resource.ResourceStatus.V(1)
        ERROR = Resource.ResourceStatus.V(2)

    USEFUL = Resource.ResourceStatus.V(0)
    EMPTY = Resource.ResourceStatus.V(1)
    ERROR = Resource.ResourceStatus.V(2)

    class TextsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        @property
        def value(self) -> global___TextInformation: ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Optional[global___TextInformation] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    class ParagraphsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text = ...
        @property
        def value(self) -> global___Paragraphs: ...
        def __init__(self,
            *,
            key : typing.Text = ...,
            value : typing.Optional[global___Paragraphs] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    RESOURCE_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    TEXTS_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    PARAGRAPHS_FIELD_NUMBER: builtins.int
    PARAGRAPHS_TO_DELETE_FIELD_NUMBER: builtins.int
    SENTENCES_TO_DELETE_FIELD_NUMBER: builtins.int
    RELATIONS_FIELD_NUMBER: builtins.int
    RELATIONS_TO_DELETE_FIELD_NUMBER: builtins.int
    @property
    def resource(self) -> global___ResourceID: ...
    @property
    def metadata(self) -> global___Metadata: ...
    @property
    def texts(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___TextInformation]:
        """Doc index
        Tantivy doc filled by field allways full
        """
        pass
    @property
    def labels(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """Key is RID/FIELDID

        Document labels allways serialized full
        """
        pass
    status: global___Resource.ResourceStatus.V = ...
    """Tantivy doc"""

    @property
    def paragraphs(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___Paragraphs]:
        """Paragraph
        Paragraphs by field
        """
        pass
    @property
    def paragraphs_to_delete(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def sentences_to_delete(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def relations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[nucliadb_protos.utils_pb2.Relation]:
        """Relations"""
        pass
    @property
    def relations_to_delete(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[nucliadb_protos.utils_pb2.Relation]: ...
    def __init__(self,
        *,
        resource : typing.Optional[global___ResourceID] = ...,
        metadata : typing.Optional[global___Metadata] = ...,
        texts : typing.Optional[typing.Mapping[typing.Text, global___TextInformation]] = ...,
        labels : typing.Optional[typing.Iterable[typing.Text]] = ...,
        status : global___Resource.ResourceStatus.V = ...,
        paragraphs : typing.Optional[typing.Mapping[typing.Text, global___Paragraphs]] = ...,
        paragraphs_to_delete : typing.Optional[typing.Iterable[typing.Text]] = ...,
        sentences_to_delete : typing.Optional[typing.Iterable[typing.Text]] = ...,
        relations : typing.Optional[typing.Iterable[nucliadb_protos.utils_pb2.Relation]] = ...,
        relations_to_delete : typing.Optional[typing.Iterable[nucliadb_protos.utils_pb2.Relation]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["metadata",b"metadata","resource",b"resource"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["labels",b"labels","metadata",b"metadata","paragraphs",b"paragraphs","paragraphs_to_delete",b"paragraphs_to_delete","relations",b"relations","relations_to_delete",b"relations_to_delete","resource",b"resource","sentences_to_delete",b"sentences_to_delete","status",b"status","texts",b"texts"]) -> None: ...
global___Resource = Resource
