[tool.poetry]
name = "cloops"
version = "0.0.3"
description = "sadasdasd"
authors = ["Your Name <you@example.com>"]
license = "asdasdasd"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
