# This file was auto-generated by Shut. DO NOT EDIT
# For more information about Shut, check out https://pypi.org/project/shut/

from __future__ import print_function
import io
import os
import setuptools
import sys

readme_file = 'readme.md'
if os.path.isfile(readme_file):
  with io.open(readme_file, encoding='utf8') as fp:
    long_description = fp.read()
else:
  print("warning: file \"{}\" does not exist.".format(readme_file), file=sys.stderr)
  long_description = None

requirements = [
  'databind.json >=1.3.2,<2.0.0',
  'nr.util >=0.2.1,<1.0.0',
  'pyyaml >=5.4.0,<6.0.0',
]
test_requirements = [
  'types-pyyaml',
]
extras_require = {}
extras_require['fastapi'] = [
  'fastapi >=0.70.1,<1.0.0',
]
extras_require['test'] = test_requirements

setuptools.setup(
  name = 'cytonic',
  version = '0.2.0',
  author = 'Niklas Rosenstein',
  author_email = 'rosensteinniklas@gmail.com',
  description = 'A Python framework to define REST APIs and automatically generate server side bindings and clients.',
  long_description = long_description,
  long_description_content_type = 'text/markdown',
  url = 'https://gitea.nkl.st/_/cytonic',
  license = 'MIT',
  packages = setuptools.find_packages('src', ['test', 'test.*', 'tests', 'tests.*', 'docs', 'docs.*']),
  package_dir = {'': 'src'},
  include_package_data = True,
  install_requires = requirements,
  extras_require = extras_require,
  tests_require = test_requirements,
  python_requires = '>=3.10.0,<4.0.0',
  data_files = [],
  entry_points = {
    'console_scripts': [
      'cytonic-codegen-python = cytonic.codegen.python:main',
    ]
  },
  cmdclass = {},
  keywords = [],
  classifiers = [],
  zip_safe = False,
)
