[tool.poetry]
name = "cfn_lint_serverless"
version = "0.3.2"
description = "Serverless rules for cfn-lint"
authors = ["Amazon Web Services"]
readme = "README.md"
license = "MIT-0"

[tool.poetry.dependencies]
python = ">=3.6.2,<4"
cfn-lint = ">=0.49.2,<1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
isort = "^5.7.0"
black = "^21.12b0"
flake8 = "^4.0.1"
coverage = "^6.2"
flake8-variables-names = "^0.0.4"
pytest-cov = "^3.0.0"
flake8-eradicate = "^1.2.0"
flake8-bugbear = "^22.1.11"
bandit = "^1.7.0"
radon = "^5.1.0"
xenon = "^0.8.0"

[tool.black]
line-length = 120
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | example
)
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
