# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\test-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2021-12-23 14:21:19.678184
__version__ = '3.2.5.dev1'