
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-11T18:49:17-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "db87008aa6649d3d21b79ae97ea0f11d7f1f1935",
 "version": "1.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
