
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-12T12:54:10+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "acf08a0151c88081a4c62356c3b2295c43a9d131",
 "version": "0.2.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
