[build-system]
requires = ["poetry-core >=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
substitution.files = ["src/instawow/_version.py"]

[tool.poetry]
name = "instawow"
version = "1.37.0"
description = "World of Warcraft add-on manager"
license = "GPL-3.0-or-later"
authors = [
  "layday <layday@protonmail.com>",
]
readme = "README.rst"
urls.homepage = "http://github.com/layday/instawow"
packages = [
  { include = "instawow", from = "src" },
  { include = "instawow_gui", from = "gui-webview/src" },
]
include = [
  { path = "COPYING", format = "sdist" },
  { path = "gui-webview/src/instawow_gui/frontend/*" },
  { path = "gui-webview/src/instawow_gui/webview2/*" },
  { path = "tests", format = "sdist" },
]
scripts.instawow = "instawow.cli:main"

[tool.poetry.dependencies]
python = ">=3.7"

aiohttp = ">=3.7.4, <4"
alembic = ">=1.7.0"
click = ">=8.0.0"
jinja2 = ">=3.0.0"
loguru = ">=0.5.3"
pluggy = ">=0.13"
prompt-toolkit = ">=3.0.15, <4"
pydantic = ">=1.9.0, <2"
questionary = ">=1.10"
rapidfuzz = ">=1.4.1"
sqlalchemy = ">=1.4.23"
typing-extensions = ">=4.0.0"
yarl = ">=1.6.3"

aiohttp-rpc = { version = ">=1.0.0", optional = true }
toga = { version = ">=0.3.0.dev30", optional = true }

aresponses = { version = ">=2.1.4 ", optional = true }
coverage = { version = ">=6.2", extras = ["toml"], optional = true }
pytest = { version = ">=6.2.5", optional = true }
pytest-asyncio = { version = ">=0.16.0", optional = true }
pytest-xdist = { version = ">=2.5.0", optional = true }

sqlalchemy2-stubs = { version = "*", optional = true }

[tool.poetry.extras]
gui = [
  "aiohttp-rpc",
  "toga",
]
test = [
  "aresponses",
  "coverage",
  "pytest",
  "pytest-asyncio",
  "pytest-xdist",
]
types = [
  "sqlalchemy2-stubs",
]


## TESTING ##

[tool.coverage.run]
source_pkgs = [
  "instawow",
]
omit = [
  "**/instawow/migrations/*",
]
parallel = true
branch = true
dynamic_context = "test_function"

[tool.coverage.paths]
combine = ["src/instawow", "**/instawow"]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "raise NotImplementedError",
  "@overload"
]

[tool.pytest.ini_options]
markers = [
  "iw_no_mock_http",
]
xfail_strict = true
filterwarnings = [
  "error",
  "once::DeprecationWarning:asyncio.base_events",
]


## TYPE CHECKING ##

[tool.pyright]
include = [
  "src",
  "gui-webview/src",
]
ignore = [
  "src/instawow/migrations",
  "gui-webview/src/instawow_gui/webview2_adapter.py",
]
strict = ["src"]


## FORMATTING ##

[tool.black]
line_length = 99
skip_string_normalization = true
target_version = ["py37", "py38", "py39", "py310"]

[tool.isort]
profile = "black"
line_length = 99
force_sort_within_sections = true
